#!/bin/bash
./mvnw clean package -P postgres
java -Djava.security.manager \
-Djava.security.krb5.realm=HOPTO.ORG \
-Djava.security.krb5.kdc=kerbserver.hopto.org \
-Djava.security.auth.login.config=$HOME/jaas.conf \
-Djava.security.policy=$HOME/jaasacn.policy \
-jar target/kerberos-authenticate-authorize-1.0.0-SNAPSHOT.jar \
ru.fintech.kerberos.tutorial.actions.AuthorizedConnection
